uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':');

external_components:
  - source:
      type: git
      url: https://github.com/lipov3cz3k/esphome-bspool-chlorinator
    components: [ bs_pool ]

bs_pool:
  update_interval: 5s

sensor:
  - platform: bs_pool
    cell_current:
      name: Cell current
    cell_intensity:
      name: Cell intensity
    cell_voltage:
      name: Cell voltage
    ph:
      name: pH
    salt_concentration:
      name: Salt concentration
    time:
      name: Device Time
    version:
      name: Device firmware version
