name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: ESP8266
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install ESPHome
        run: pip install esphome
      - name: Validate config
        run: esphome config tests/components/bs_pool/test.esp8266-ard.yaml
      - name: Build firmware
        uses: esphome/build-action@v7
        with:
          yaml-file: tests/components/bs_pool/test.esp8266-ard.yaml
